### ISSUE TITLE
Viikko2 Vertaisarviointi

### ISSUE THREAD

**Issue by matiasto** [MatiasSinisalo/tietokantasovellus-oppinaytetyo#1]
Sovelluksen toiminta

-	Salasana näkyvissä tunnusta luodessa. Korjausehdotus:      input type=”password”
-	Tunnuksen luonnissa ei ole mitään viitteitä onko jokin tieto pakollinen (näköjään kaikki).
-	Tunnuksen luonnin epäonnistuminen tai onnistuminen näyttää samalta käyttäjälle. Voisi indikoida jollakin viestillä onnistuiko vai ei.
-	Kirjan lukeminen aiheutti joka kerralla INTERNAL SERVER ERROR.
-	Lainaaminen ja palautus toimii hyvin, saldot päivittyvät oikein jne.
-	Käyttäjän luominen ja kirjautuminen toimii perusteiltaa hyvin.

Sovelluksen rakenteesta

-	Scheemaan voisi lisätä sisäisiä UNIQUE rajoitteita varmistamaan tiedon yksilöllisyyden. Huomaa, että UNIQUE rajoite voi ottaa parametrina monta kolumnia https://www.postgresqltutorial.com/postgresql-tutorial/postgresql-unique-constraint/ 
-	Molemmat app.py ja query.py luovat oman Flask-instanssin. Kannattaa ehdottomasti poistaa se query.py:stä ja importoida se app.py:stä. Voi olla, että sovelluksen server errorilla oli joitain kytköksiä tämän kanssa.
-	Ehdottomasti kannattaa aloittaa sovelluslogiikan hajauttaminen. Tällä hetkellä app.py ja query.py alkavat olla melko ruuhkaisia. Kurssimateriaalissa ja referenssisovelluksesa on hyviä ideoita, miten tämä kannattaa toteuttaa.
-	Kokonaisuudessaa hyvän näköistä koodia! Tsemppiä tulevaan.

**Comment by MatiasSinisalo** [comment]
Hei

Kiitos paljon hyvästä palautteesta ja aijon aloittaa ehdottamiesi korjauksien toteuttamisen.

Selvitin syytä kirjan lukemisen "Internal server error" virheelle ja syyksi osoittautui Herokun palvelimen toiminta tapa.

Heroku käynnistyy uudelleen 24 tunnin välein ja käynnistyessään uudelleen clonaa sovellukselle asetetun git repositorion. 

Jos sovelluksen käynnissäoloaikana sovellus tallentaa Herokun tallennustilaan tiedoston, niin 24 tunnin päästä palvelimella oleva tiedosto tuhoutuu, koska se ei ole sovellukselle osoitetussa gitissä, vaan pelkästään Herokupalvelimen paikallisessa muistissa.

Herokulla on artikkeli tästä asiasta:
https://help.heroku.com/K1PPS2WM/why-are-my-file-uploads-missing-deleted-from-the-application 

Onneksi tämä bugi löytyi sillä se olisi voinut jäädä hyvin huomaamatta.

**Comment by matiasto** [comment]
Hyvä kun selvisi! 
Aika mielenkiintoinen ongelma ja kiva kun laitoit follow uppia, aina oppii jotain uutta.
